### PR TITLE
Added more logging options

### PR DESCRIPTION
**Pull request by Awire9966**
Added advanced logging abilities. In the JSON file, the logging mode is by default "stdout"
 aka console. you can replace that with a file path to log to a file instead of flooding your console.

### CODE REVIEW

**Comment by ImKventis** [comment]
This undoes commit f717dec and e5547f7

**Comment by Awire9966** [comment]
@ImKventis Thank you for mentioning, i will sync those commits

**Comment by Awire9966** [comment]
@ImKventis Consider it fixed.

**Comment by conaticus** [comment]
Thanks for your PR, I will be closing it because it has a bunch of syntax errors and is ultimately broken. Please test your code before submitting.

**Comment by Awire9966** [comment]
Understood... it worked for me but I will try to figure out what's wrong

**Pull request closed without merging**
