### PR TITLE
Added Logging options (FIXED FROM #36)

### PR DESCRIPTION
**Pull request by Awire9966**
Hello! I have fixed all the issues of #36 so we should be bug free from my end.

Heres how my update works.

In the appsettings.json there is  a new item called ```"LogMode"```
LogMode is by default set to stdout like this: 
```
"LogMode": "stdout"
```
LogMode can also be set to a file path:
```
"LogMode": "C:\My Awesome Boolean Log.txt"
```
In filepath mode, it will add to that file. The file is plaintext, so any text editor should be able to open it.
NOTICE FOR FILE EXAMPLE: WONT WORK UNLESS RAN WITH ADMIN PERMISSIONS AS THE PROGRAM NEEDS PERMISSION TO WRITE TO C:. Dont be surprised if it doesnt work.

### CODE REVIEW

**Comment by dylhack** [comment]
@Awire9966 reopen with rebase on develop we just added gh actions

**Comment by conaticus** [comment]
Also we don't need this because docker can show logs for us.

**Comment by Awire9966** [comment]
https://github.com/conaticusgrp/boolean/pull/48#issuecomment-2118855145 idk what rebase means.

**Comment by dylhack** [comment]
start fresh with the latest commit on the develop branch

**Pull request closed without merging**
